language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    - rust: stable
  fast_finish: true
cache: cargo

jobs:
  include:
    - stage: "Test"
      script: cargo test --verbose --all
    - stage: "Build"
      script: cargo build --verbose --all
