language: rust
rust: nightly

before_install:
  - sudo apt-get -y update
  - sudo apt-get install -y jq cmake pkg-config libssl-dev git gcc build-essential clang libclang-dev

jobs:
  include:
    - stage: Build
      script: cargo build --verbose --all
    - stage: UT Test
      script:  cargo test  --verbose
    - stage: Cli Test
      script: ./test.sh
