language: rust
rust:
  - stable
  - nightly

before_install:
  - sudo apt-get -y update
  - sudo apt-get install -y

# Yes, use nightly as default
matrix:
  allow_failures:
    - rust: stable
  fast_finish: true
cache: cargo

jobs:
  include:
    - stage: "Test"
      script: cargo test --verbose --all
    - stage: "Test"
      script: test.sh
    - stage: "Build"
      script: cargo build --verbose --all
