[package]
name = "ssi"
version = "0.1.0"
authors = ["Antonio Yang <yanganto@gmail.com>"]
edition = "2018"
description = "Substrate Storage Inspector"


[dependencies]
rocksdb = "0.14.0"
array-bytes = { git = "https://github.com/darwinia-network/darwinia-common.git" }
